package hospitalmanagementsystem;
/*
 /**
 * This class shows the list of patients from database
 *
 * @author Melih Obut
 * @author Ege Kaan Eren
 * @date 2019.12.21
 */
public class ManagerPanel extends javax.swing.JFrame {

	   String userName;
	    int id;
	    String password;
    /**
     * Creates new form ReceptionistPanel
     */
    public ManagerPanel() {
        initComponents();
    }
     /**
     * Constructor of ManagerPanel that initializes variables
     */
    public ManagerPanel(int id, String name, String pass)
    {
    	this.id = id;
    	this.userName = name;
    	this.password = pass;
    	initComponents();
    	ManagerName.setText(userName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ManagerName = new javax.swing.JLabel();
        IncomesButton = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();
        PatientGeneralInfoButton = new javax.swing.JButton();
        SettingDoctorListButton = new javax.swing.JButton();
        EquipmentNumbersButton = new javax.swing.JButton();
        DoctorListButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        ManagerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManagerName.setText("Manager Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(418, Short.MAX_VALUE)
                .addComponent(ManagerName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(406, 406, 406))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(ManagerName)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 31, 1000, 84);

        IncomesButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        IncomesButton.setText("Expenses/Incomes");
        IncomesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncomesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(IncomesButton);
        IncomesButton.setBounds(580, 230, 220, 54);

        SettingsButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        SettingsButton.setText("Settings");
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SettingsButton);
        SettingsButton.setBounds(580, 330, 220, 54);

        PatientGeneralInfoButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        PatientGeneralInfoButton.setText("Patient List");
        PatientGeneralInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientGeneralInfoButtonActionPerformed(evt);
                new PatientList().setVisible(true);
            }
        });
        getContentPane().add(PatientGeneralInfoButton);
        PatientGeneralInfoButton.setBounds(200, 130, 220, 54);

        SettingDoctorListButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        SettingDoctorListButton.setText("Setting Doctor List");
        SettingDoctorListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingDoctorListButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SettingDoctorListButton);
        SettingDoctorListButton.setBounds(200, 330, 220, 54);

        EquipmentNumbersButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        EquipmentNumbersButton.setText("Equipment Numbers");
        EquipmentNumbersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipmentNumbersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EquipmentNumbersButton);
        EquipmentNumbersButton.setBounds(578, 133, 220, 54);

        DoctorListButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        DoctorListButton.setText("Doctor List");
        DoctorListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorListButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorListButton);
        DoctorListButton.setBounds(200, 230, 220, 54);

        BackButton.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(712, 494, 86, 41);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\arkaplan.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 550);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1000, 575));
		setResizable(true);
		setSize(new java.awt.Dimension(1000, 575));
        setLocationRelativeTo(null);
   //     pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PatientGeneralInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientGeneralInfoButtonActionPerformed
        new PatientGeneralInfoPanel().setVisible(true);
    }//GEN-LAST:event_PatientGeneralInfoButtonActionPerformed

    private void DoctorListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorListButtonActionPerformed
        new DoctorListPanel().setVisible(true);
    }//GEN-LAST:event_DoctorListButtonActionPerformed

    private void EquipmentNumbersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipmentNumbersButtonActionPerformed
        new Equipment().setVisible(true);
    }//GEN-LAST:event_EquipmentNumbersButtonActionPerformed

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
      	setVisible(false);
        new Settings(id, userName, password, "manager").setVisible(true);
    }//GEN-LAST:event_SettingsButtonActionPerformed

     /**
     * This method give opportunity to show incomes and expenses
     */
    private void IncomesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncomesButtonActionPerformed
        new ExpencesAndIncomes().setVisible(true);
    }//GEN-LAST:event_IncomesButtonActionPerformed
    
     /**
     * This method makes unvisibile
     */
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
    	setVisible(false);
    	new AdminMain().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed
    
     /**
     * This method makes visible doctorpanel
     */
    private void SettingDoctorListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingDoctorListButtonActionPerformed
        new AddDoctorPanel().setVisible(true);
    }//GEN-LAST:event_SettingDoctorListButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DoctorListButton;
    private javax.swing.JButton EquipmentNumbersButton;
    private javax.swing.JButton IncomesButton;
    private javax.swing.JLabel ManagerName;
    private javax.swing.JButton PatientGeneralInfoButton;
    private javax.swing.JButton SettingDoctorListButton;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
